# Site settings
title: Steve' Blog
SEOTitle: 饶子昊的博客 | SteveRao' Blog
header-img: img/home-bg.jpg
email: zihaorao@126.com
description: "饶子昊，Web & Software Engineer| 这里是 @Steve饶子昊 的个人博客，与你一起发现更大的世界。"
keyword: "Steve, @Steve饶子昊, @zihaorao 饶子昊的博客, SteveRao Blog, 饶子昊, 博客, 个人网站, 互联网, Java, 大数据，分布式，云原生， 后端, Java开发者"
url: "https://steverao.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: ZihaoRao
#zhihu_username:     
github_username: steverao
#twitter_username:   
#facebook_username:  
linkedin_username: in/子昊-饶-9331a1175



# Build settings
# from 2018, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: steve

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
ba_track_id: 'faa5974e50cd17f6e1e966846511d43b'

# Google Analytics
ga_track_id: 'UA-127261700-1'            # Format: UA-xxxxxx-xx
ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "知识和方法可以借助别人，但创作的智慧全靠自己!"
sidebar-avatar: /img/avatar-steve-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1           # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Relevant links
relevant-links: [
    {
        title: "Spring",
        href: "https://github.com/spring-projects/spring-framework"
    },{
        title: "掘金",
        href: "https://juejin.im/welcome"
    },{
        title: "LeetCode",
        href: "https://leetcode-cn.com/"
    },{
        title: "InfoQ",
        href: "http://www.infoq.cn/"
    },{
        title: "Kubernetes",
        href: "https://github.com/kubernetes/kubernetes"
    },{
        title: "Hadoop",
        href: "https://github.com/apache/hadoop"
    },{
        title: "Spark",
        href: "https://github.com/apache/spark"
    },{
        title: "Kafka",
        href: "https://github.com/apache/kafka"
    },{
        title: "Dubbo",
        href: "https://github.com/apache/dubbo"
    },{
        title: "阿里中间件团队",
        href: "http://jm.taobao.org/"
    },{
        title: "美团技术团队",
        href: "https://tech.meituan.com/"
    }
]

